title: MK316.github.io
logo: /images/mainlogo01.png
description: I am a researcher in Phonetics & Phonology and an educator in the Department of English Education at GNU. My work explores speech sound production, perception, linguistic patterns, and digital literacy education for English teachers. This site provides research insights, educational resources, and academic updates for students and scholars.    
description: mirankim316@gmail.com
show_downloads: true
theme: jekyll-theme-minimal  
