title: MK316.github.io (Weblog)
logo: /images/mainlogo01.png
description: I'm a researcher specialized in Phonetics & Phonology. [mailto](mailto: MK3one6@gmail.com)  
show_downloads: true
theme: jekyll-theme-minimal  
