title: MK316.github.io
logo: /images/mainlogo01.png
description: I am a Phonetics & Phonology researcher and educator in English Education at GNU, focusing on speech sounds, linguistic patterns, and digital literacy for English teachers.  
show_downloads: true
theme: jekyll-theme-minimal  
