title: MK316.github.io
logo: /images/mainlogo01.png
description: Hello. I'm a researcher specialized in Phonetics & Phonology. (💬 This website started since May 2022.)    
show_downloads: true
theme: jekyll-theme-minimal  
