title: MK316.github.io
logo: /images/mainlogo01.png
description: I am a Phonetics & Phonology researcher and educator affiliated with the Dept. of English Education at GNU. My research focuses on speech sounds, prosodic characteristics of languages, pronunciation teaching and digital literacy training for English teachers.  
show_downloads: true
theme: jekyll-theme-minimal  
