title: MK316.github.io
logo: /images/mainlogo01.png
description: I am a Phonetics & Phonology researcher and educator in English Education at [GNU](https://englishedu.gnu.ac.kr), focusing on speech sounds, linguistic patterns, and digital literacy for English teachers. This site offers research insights, educational resources, and academic updates.  
show_downloads: true
theme: jekyll-theme-minimal  
