title: MK316.github.io (Weblog)
logo: /images/snow.jpg
description: I'm a researcher specialized in Phonetics & Phonology.
show_downloads: true
theme: jekyll-theme-minimal

# Footer Links
footer_links:
  - title: Miran Kim
    email: MK3one6@gmail.com
